name: mls_fixed
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-build=25.1.2
  - numpy<2
  - numba=0.61
  - pytest
  - tqdm
  - scikit-learn=1.6.1
  - pandas=2.2.3
  - matplotlib=3.10.1
  - pip            # must list pip so conda installs it
  - pip:
    - jax==0.6.2
    - jaxlib==0.6.2
    - jax_cuda12_plugin==0.6.2
    - jax-finufft
